preload = /home/jrodriiguezg/.config/hypr/wallpapers/image.jpg

wallpaper = eDP-1,/home/jrodriiguezg/.config/hypr/wallpapers/image.jpg
wallpaper = HDMI-A-1,/home/jrodriiguezg/.config/hypr/wallpapers/image.jpg

splash = false
ipc = on
